name: Feature Request
description: Suggest a new feature or enhancement for the Incident Command Center
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What is the current limitation or pain point?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or workarounds?
      placeholder: Describe any alternative solutions or workarounds you've considered

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the app would this feature affect?
      options:
        - Dashboard/UI
        - Navigation/Controls
        - API Integration
        - Security/Authentication
        - Settings/Configuration
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your use case?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Description
      description: Describe how you would use this feature in your workflow
      placeholder: Walk us through a typical scenario where this feature would be helpful
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Visual Mockup/Design Ideas
      description: If you have ideas about how this should look or work, describe them here
      placeholder: Describe the UI/UX or attach mockups if you have them

  - type: checkboxes
    id: considerations
    attributes:
      label: Apple TV Considerations
      description: Please consider these Apple TV specific constraints
      options:
        - label: This feature works well with Apple TV remote navigation
        - label: This feature is readable from across the room (large text/high contrast)
        - label: This feature doesn't require complex text input
        - label: This feature maintains the "war room display" concept

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Who would benefit from this feature and how?
      placeholder: Describe the potential impact on users, teams, or incident response workflows

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or examples that would help us understand this request